name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run : echo â€œğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event.â€
      - run : echo â€œğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!â€
      - run : echo â€œğŸš€ The ${{ github.repository }} repository has been cloned to the runner.â€
      - run : echo â€œğŸ’¡ The workflow is now ready to test out the Action!â€
      - run : echo â€œğŸ–¥ï¸ The runner is set up and ready to run the job!â€

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - run : echo â€œğŸ This jobâ€™s status is now ${{ job.status }}.â€